version: '3'
services:
  redis:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: redis_redisson
    environment:
        - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
