version: '3'
services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis_redisson
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    hostname: redis
  camunda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camunda_paramdo
    ports:
      - "8080:8080"
    depends_on:
        - redis
    links:
      - redis:redis
